title: Leaf Blog
iconURL: images/default-icon.png
theme: jekyll-theme-leaf

# for a clean URL
permalink: :slug

social:
  twitter: sorria62304646
  github: JasonSorria

plugins:
 - jekyll-feed
 - jekyll-seo-tag

### comments & analytics
# hyvor_talk_website_id: 14
hyvor_talk_website_id: 263
# google_analytics: UA-NNNNNNNN-N
google_analytics: UA-159848324-1
